<?php
// database/seeders/ServiceProviderSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ServiceProvider;

class ServiceProviderSeeder extends Seeder
{
    public function run(): void
    {
$providers = [
            // Traditional Mechanics
            [
                'name' => 'AutoCare Elite',
                'type' => 'mechanic',
                'phone' => '(555) 123-4567',
                'email' => 'contact@autocareelite.com',
                'address' => '123 Main Street',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'zip_code' => '90001',
                'latitude' => 34.0522,
                'longitude' => -118.2437,
                'services_offered' => 'Oil changes, brake service, engine diagnostics, tire rotation, general maintenance',
                'rating' => 4.8,
                'total_reviews' => 245,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Premium Motors Service Center',
                'type' => 'dealership',
                'phone' => '(555) 234-5678',
                'email' => 'service@premiummotors.com',
                'address' => '456 Auto Plaza',
                'city' => 'San Francisco',
                'state' => 'CA',
                'zip_code' => '94102',
                'latitude' => 37.7749,
                'longitude' => -122.4194,
                'services_offered' => 'Full dealership services, warranty work, recall repairs, OEM parts',
                'rating' => 4.6,
                'total_reviews' => 189,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Quick Fix Auto Shop',
                'type' => 'mechanic',
                'phone' => '(555) 345-6789',
                'email' => 'info@quickfixauto.com',
                'address' => '789 Service Road',
                'city' => 'San Diego',
                'state' => 'CA',
                'zip_code' => '92101',
                'latitude' => 32.7157,
                'longitude' => -117.1611,
                'services_offered' => 'Quick oil changes, brake service, battery replacement, inspections',
                'rating' => 4.5,
                'total_reviews' => 156,
                'is_verified' => true,
                'is_active' => true,
            ],

            // ELECTRIC VEHICLE SPECIALISTS
            [
                'name' => 'Tesla Service Center LA',
                'type' => 'ev_specialist',
                'phone' => '(555) 888-8888',
                'email' => 'service@tesla-la.com',
                'address' => '2500 Olympic Blvd',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'zip_code' => '90006',
                'latitude' => 34.0259,
                'longitude' => -118.3106,
                'services_offered' => 'Tesla-certified repairs, battery diagnostics, high-voltage system service, software updates, charging port maintenance, regenerative brake service, electric motor diagnostics',
                'rating' => 4.9,
                'total_reviews' => 523,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Volt EV Service',
                'type' => 'ev_specialist',
                'phone' => '(555) 777-3000',
                'email' => 'contact@voltevservice.com',
                'address' => '890 Market Street',
                'city' => 'San Francisco',
                'state' => 'CA',
                'zip_code' => '94103',
                'latitude' => 37.7833,
                'longitude' => -122.4167,
                'services_offered' => 'All-electric vehicle service, battery health checks, EV diagnostics, charging system repairs, high-voltage cable inspection, electric drivetrain service, thermal management systems',
                'rating' => 4.8,
                'total_reviews' => 387,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'EcoCharge EV Center',
                'type' => 'ev_specialist',
                'phone' => '(555) 666-2100',
                'email' => 'service@ecocharge.com',
                'address' => '1234 Innovation Way',
                'city' => 'San Diego',
                'state' => 'CA',
                'zip_code' => '92121',
                'latitude' => 32.9083,
                'longitude' => -117.1978,
                'services_offered' => 'Electric vehicle maintenance, battery replacement, regenerative braking system service, coolant system maintenance, 12V battery service, tire rotation, cabin air filters, software diagnostics',
                'rating' => 4.7,
                'total_reviews' => 298,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Lightning EV Repair',
                'type' => 'ev_specialist',
                'phone' => '(555) 555-9900',
                'email' => 'info@lightningevrepair.com',
                'address' => '567 Electric Avenue',
                'city' => 'Sacramento',
                'state' => 'CA',
                'zip_code' => '95814',
                'latitude' => 38.5816,
                'longitude' => -121.4944,
                'services_offered' => 'EV-certified technicians, battery pack diagnostics, electric motor repair, inverter service, charging port installation and repair, thermal cooling system maintenance, brake fluid service',
                'rating' => 4.6,
                'total_reviews' => 215,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Rivian Service Hub',
                'type' => 'ev_specialist',
                'phone' => '(555) 444-7700',
                'email' => 'service@rivian-hub.com',
                'address' => '3456 Green Tech Parkway',
                'city' => 'Oakland',
                'state' => 'CA',
                'zip_code' => '94607',
                'latitude' => 37.8044,
                'longitude' => -122.2712,
                'services_offered' => 'Rivian-specialized service, adventure vehicle maintenance, battery conditioning, quad-motor diagnostics, air suspension service, off-road system checks, software updates',
                'rating' => 4.9,
                'total_reviews' => 412,
                'is_verified' => true,
                'is_active' => true,
            ],

            // HYBRID & EV CAPABLE SHOPS
            [
                'name' => 'Green Auto Works',
                'type' => 'mechanic',
                'phone' => '(555) 333-6600',
                'email' => 'contact@greenautoworks.com',
                'address' => '789 Eco Drive',
                'city' => 'San Jose',
                'state' => 'CA',
                'zip_code' => '95113',
                'latitude' => 37.3382,
                'longitude' => -121.8863,
                'services_offered' => 'Hybrid and electric vehicle service, traditional auto repair, battery diagnostics, brake service, tire rotation, AC service, general maintenance for all vehicle types',
                'rating' => 4.7,
                'total_reviews' => 342,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Future Motors Service',
                'type' => 'dealership',
                'phone' => '(555) 222-5500',
                'email' => 'service@futuremotors.com',
                'address' => '1000 Dealer Boulevard',
                'city' => 'Fresno',
                'state' => 'CA',
                'zip_code' => '93721',
                'latitude' => 36.7378,
                'longitude' => -119.7871,
                'services_offered' => 'Multi-brand EV and hybrid service, dealership warranty work, battery health monitoring, software updates, traditional services, certified EV technicians on staff',
                'rating' => 4.5,
                'total_reviews' => 276,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Spark EV Solutions',
                'type' => 'ev_specialist',
                'phone' => '(555) 111-4400',
                'email' => 'info@sparkev.com',
                'address' => '2222 Battery Street',
                'city' => 'Long Beach',
                'state' => 'CA',
                'zip_code' => '90802',
                'latitude' => 33.7701,
                'longitude' => -118.1937,
                'services_offered' => 'Mobile EV service, on-site diagnostics, battery testing, charging system repairs, emergency roadside assistance, preventive maintenance, fleet EV service',
                'rating' => 4.8,
                'total_reviews' => 391,
                'is_verified' => true,
                'is_active' => true,
            ],

            // BODY SHOPS WITH EV EXPERIENCE
            [
                'name' => 'Electric Body Works',
                'type' => 'body_shop',
                'phone' => '(555) 999-3300',
                'email' => 'contact@electricbodyworks.com',
                'address' => '4567 Collision Center Rd',
                'city' => 'Anaheim',
                'state' => 'CA',
                'zip_code' => '92805',
                'latitude' => 33.8366,
                'longitude' => -117.9143,
                'services_offered' => 'EV collision repair, aluminum body work, high-voltage system disconnect protocols, Tesla-certified body repairs, paint and detailing, insurance claims',
                'rating' => 4.6,
                'total_reviews' => 198,
                'is_verified' => true,
                'is_active' => true,
            ],

            // DETAILING SERVICES
            [
                'name' => 'Premium EV Detailing',
                'type' => 'detailing',
                'phone' => '(555) 888-2200',
                'email' => 'booking@premiumevdetailing.com',
                'address' => '789 Shine Boulevard',
                'city' => 'Santa Monica',
                'state' => 'CA',
                'zip_code' => '90401',
                'latitude' => 34.0195,
                'longitude' => -118.4912,
                'services_offered' => 'EV-safe detailing, ceramic coating, interior sanitization, waterless wash options, paint protection film, wheel cleaning, battery cover cleaning, mobile detailing',
                'rating' => 4.9,
                'total_reviews' => 567,
                'is_verified' => true,
                'is_active' => true,
            ],
        ];

        foreach ($providers as $provider) {
            ServiceProvider::create($provider);
        }

        $this->command->info('Service providers seeded successfully!');
    }
}