<?php
// database/seeders/ServiceProviderSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ServiceProvider;

class ServiceProviderSeeder extends Seeder
{
    public function run(): void
    {
        $providers = [
            [
                'name' => 'AutoCare Elite',
                'type' => 'mechanic',
                'phone' => '(555) 123-4567',
                'email' => 'contact@autocareelite.com',
                'address' => '123 Main Street',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'zip_code' => '90001',
                'latitude' => 34.0522,
                'longitude' => -118.2437,
                'services_offered' => 'Oil changes, brake service, engine diagnostics, tire rotation, general maintenance',
                'rating' => 4.8,
                'total_reviews' => 245,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Premium Motors Service Center',
                'type' => 'dealership',
                'phone' => '(555) 234-5678',
                'email' => 'service@premiummotors.com',
                'address' => '456 Auto Plaza',
                'city' => 'San Francisco',
                'state' => 'CA',
                'zip_code' => '94102',
                'latitude' => 37.7749,
                'longitude' => -122.4194,
                'services_offered' => 'Full dealership services, warranty work, recall repairs, OEM parts',
                'rating' => 4.6,
                'total_reviews' => 189,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Quick Fix Auto Shop',
                'type' => 'mechanic',
                'phone' => '(555) 345-6789',
                'email' => 'info@quickfixauto.com',
                'address' => '789 Service Road',
                'city' => 'San Diego',
                'state' => 'CA',
                'zip_code' => '92101',
                'latitude' => 32.7157,
                'longitude' => -117.1611,
                'services_offered' => 'Quick oil changes, brake service, battery replacement, inspections',
                'rating' => 4.5,
                'total_reviews' => 156,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Precision Body Works',
                'type' => 'body_shop',
                'phone' => '(555) 456-7890',
                'email' => 'contact@precisionbody.com',
                'address' => '321 Collision Avenue',
                'city' => 'Sacramento',
                'state' => 'CA',
                'zip_code' => '95814',
                'latitude' => 38.5816,
                'longitude' => -121.4944,
                'services_offered' => 'Collision repair, dent removal, painting, frame straightening',
                'rating' => 4.9,
                'total_reviews' => 98,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Shine & Detail Pro',
                'type' => 'detailing',
                'phone' => '(555) 567-8901',
                'email' => 'booking@shinedetail.com',
                'address' => '654 Clean Street',
                'city' => 'San Jose',
                'state' => 'CA',
                'zip_code' => '95110',
                'latitude' => 37.3382,
                'longitude' => -121.8863,
                'services_offered' => 'Interior/exterior detailing, ceramic coating, paint correction, headlight restoration',
                'rating' => 4.7,
                'total_reviews' => 134,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => '24/7 Towing Services',
                'type' => 'towing',
                'phone' => '(555) 678-9012',
                'email' => 'dispatch@247towing.com',
                'address' => '987 Emergency Lane',
                'city' => 'Oakland',
                'state' => 'CA',
                'zip_code' => '94601',
                'latitude' => 37.8044,
                'longitude' => -122.2712,
                'services_offered' => 'Emergency towing, roadside assistance, lockout service, jump starts',
                'rating' => 4.4,
                'total_reviews' => 267,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Express Oil & Lube',
                'type' => 'mechanic',
                'phone' => '(555) 789-0123',
                'email' => 'service@expressoil.com',
                'address' => '147 Quick Lane',
                'city' => 'Fresno',
                'state' => 'CA',
                'zip_code' => '93721',
                'latitude' => 36.7378,
                'longitude' => -119.7871,
                'services_offered' => 'Oil changes, fluid top-offs, filter replacements, basic maintenance',
                'rating' => 4.3,
                'total_reviews' => 203,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'European Auto Specialists',
                'type' => 'mechanic',
                'phone' => '(555) 890-1234',
                'email' => 'info@euroautospec.com',
                'address' => '258 Import Boulevard',
                'city' => 'Long Beach',
                'state' => 'CA',
                'zip_code' => '90802',
                'latitude' => 33.7701,
                'longitude' => -118.1937,
                'services_offered' => 'BMW, Mercedes, Audi, VW specialist. Diagnostics, repair, maintenance',
                'rating' => 4.9,
                'total_reviews' => 178,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Tire World',
                'type' => 'mechanic',
                'phone' => '(555) 901-2345',
                'email' => 'sales@tireworld.com',
                'address' => '369 Rubber Road',
                'city' => 'Bakersfield',
                'state' => 'CA',
                'zip_code' => '93301',
                'latitude' => 35.3733,
                'longitude' => -119.0187,
                'services_offered' => 'Tire sales and installation, wheel alignment, balancing, rotation',
                'rating' => 4.6,
                'total_reviews' => 312,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Complete Auto Care',
                'type' => 'mechanic',
                'phone' => '(555) 012-3456',
                'email' => 'contact@completeautocare.com',
                'address' => '741 Mechanic Way',
                'city' => 'Riverside',
                'state' => 'CA',
                'zip_code' => '92501',
                'latitude' => 33.9533,
                'longitude' => -117.3962,
                'services_offered' => 'Full service auto repair, engine work, transmission, electrical, AC service',
                'rating' => 4.7,
                'total_reviews' => 221,
                'is_verified' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Budget Brake & Muffler',
                'type' => 'mechanic',
                'phone' => '(555) 123-7890',
                'email' => 'info@budgetbrake.com',
                'address' => '852 Economy Street',
                'city' => 'Anaheim',
                'state' => 'CA',
                'zip_code' => '92801',
                'latitude' => 33.8366,
                'longitude' => -117.9143,
                'services_offered' => 'Brake service, muffler repair, exhaust systems, suspension work',
                'rating' => 4.2,
                'total_reviews' => 145,
                'is_verified' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Luxury Car Detailing',
                'type' => 'detailing',
                'phone' => '(555) 234-8901',
                'email' => 'bookings@luxurydetail.com',
                'address' => '963 Premium Drive',
                'city' => 'Santa Monica',
                'state' => 'CA',
                'zip_code' => '90401',
                'latitude' => 34.0195,
                'longitude' => -118.4912,
                'services_offered' => 'High-end detailing, paint protection film, ceramic coating, interior restoration',
                'rating' => 5.0,
                'total_reviews' => 87,
                'is_verified' => true,
                'is_active' => true,
            ],
        ];

        foreach ($providers as $provider) {
            ServiceProvider::create($provider);
        }

        $this->command->info('Service providers seeded successfully!');
    }
}